### ISSUE TITLE
Difference between scripts 3 and 4

### ISSUE THREAD

**Issue by ellognea** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#12]
Hi Sarah,

Do you understand the difference between scripts 3 and 4 below in the context of our question ?
I have the t-test summary table in script 3.

- Third script that reads the data from the first script, performs some statistical or machine learning analysis (e.g., creates a summary table) and writes these numerical data to file in CSV or TSV format. This should take two arguments:
a path/filename pointing to the data
a path/filename where to write the file to and what to call it (e.g., results/summarized_data.csv)

- Fourth script that reads the output of the first and/or third script, generate some summary/final result table(s) and/or figure(s) and save them to files. This should take two arguments:
a path/filename pointing to the data
a path/filename prefix where to write the figure(s)/table(s) to and what to call it (e.g., results/this_analysis)

**Comment by smwatts** [comment]
For script 3 I would add the following output table (the estimates table):

![screen shot 2018-11-22 at 9 58 27 am](https://user-images.githubusercontent.com/22134649/48917746-4b631300-ee3d-11e8-90b8-2ea82d1f1b65.png)

**Comment by smwatts** [comment]
Then can use script 4 we can generate a figure:

1. A figure for the mean and confidence interval

![screen shot 2018-11-22 at 9 58 48 am](https://user-images.githubusercontent.com/22134649/48917757-561da800-ee3d-11e8-9ac3-69dc6bb4c5b4.png)

**Comment by smwatts** [comment]
I have code right now in script 2 (EDA) that generates the estimates table so I could apply the confidence intervals and means to the graph. I'm thinking that we can move that out to script 3 so all statistical calculations live there.

Then for script 2 (EDA) we could just show the violin/jitter plot (without CI/mean) and use script 4 to generate the CI/mean graph.

**Comment by smwatts** [comment]
Script 1 -> 
- input: original dataset
- output: clean_data

Script 2 ->
- input: clean_data
- output: jitter/violin plot

Script 3 -> 
- input: clean_data
- output: the estimates table & the hypothesis tests table

Script 4 -> 
- input: estimates table
- output: CI & mean plot

**Comment by ellognea** [comment]
Makes sense !
