### ISSUE TITLE
Fix project repo structure

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#13]
Repo structure can be better organized. See the slack discussion on this [HERE](https://ubc-mds.slack.com/archives/C24HUNRJL/p1542408872040400).

**Comment by smwatts** [comment]
Resolved in commit https://github.com/UBC-MDS/DSCI_522-ellognea-smwatts-student-performance/commit/0ab12b1d811d1d98f0328cc2023c496228074ab9 (submitted Nov 17th - before the submission deadline).
