### ISSUE TITLE
Graph type?

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#19]
> We'll create a visualization of the data that shows the estimate, confidence intervals and distribution for each sample. We'll also apply broom::tidy to the output of t.test to get a tidy data frame version of the results.

What type of graphs do you plan to use to visualize the "estimate, confidence intervals and distribution for each sample?"

**Comment by smwatts** [comment]
We will create two graphs: 

1. A graph that shows the distributions of the sample of final math grades by gender using a jitter/violin plot (in the EDA script)
2. A graph that shows the confidence interval and mean (estimate) for the final math grades by gender.
