### ISSUE TITLE
Additions to ReadMe

### ISSUE THREAD

**Issue by smwatts** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#3]
1. We will need to add the dependency tidyverse
2. We will need to add a link to our R script that loads the dataset 
Name: load_dataset.R
Link: https://github.com/UBC-MDS/DSCI_522-ellognea-smwatts-student-performance/blob/master/scripts/load_dataset.R

**Comment by ellognea** [comment]
Done. Thanks !
