### ISSUE TITLE
Feedback from @bsingh02 &sreyaguha

### ISSUE THREAD

**Issue by ellognea** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#30]
- Add a visualization of p-value and grades distribution in the report
- Outliers treatment: What does it mean for a student to have a final math grade of 0% ? Did they drop out ?  How much do these observations affect the mean grades ?  Test the outliers effect on the results by removing them from the data set
- Be more careful when interpreting the p-value : Mention in the report that the large number of observations might have impacted the significance.

**Comment by smwatts** [comment]
addressed in https://github.com/UBC-MDS/DSCI_522-ellognea-smwatts-student-performance/pull/31
