### ISSUE TITLE
Milestone 2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#35]
- [x]  Explain how to run the Makefile (e.g., copy repo, go to root, run these codes, etc) in your main README.md of your projects repo. 
- [x] You need a unit test for the function `violin` in the script `explore_student_perf.R`

**Comment by smwatts** [comment]
Fixed in https://github.com/UBC-MDS/DSCI_522-ellognea-smwatts-student-performance/pull/37
