### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by ellognea** [UBC-MDS/DSCI_522-ellognea-smwatts-student-performance#5]
Hi Sarah,

Di you see Tiffany's slack post on directory structure ? Do we need a doc folder ?
I think so far we have:
- readme
- src (called scripts)
-data
-results (called: report)

Let me know what you think.

**Comment by smwatts** [comment]
Resolved in: https://github.com/UBC-MDS/DSCI_522-ellognea-smwatts-student-performance/pull/7
